
strategy:
  matrix:
    Windows_3.6.8:
      vmImage: 'vs2017-win2016'
      build_name: 'Windows_3.6.8_EDM'
      python.version: '3.6.8'
    Windows_3.7.4:
      vmImage: 'vs2017-win2016'
      build_name: 'Windows_3.7.4_EDM'
      python.version: '3.7.5'
    MacOS_3.6.9:
      vmImage: 'macos-10.13'
      build_name: 'MacOS_3.6.9_EDM'
      python.version: '3.6.9'
    MacOS_3.7.4:
      vmImage: 'macos-10.13'
      build_name: 'MacOS_3.7.4_EDM'
      python.version: '3.7.5'

pool:
  vmImage: $(vmImage)
  python.version: $(python.version)

steps:
#only setup the visual studio environment if on windowz
- task: BatchScript@1
  inputs:
    filename: 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat'
    arguments: 'amd64'
    modifyEnvironment: True 
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: setup visual studio env on windows

#print which version python using for testing
- script: python --version

#build cppEDM with respective makefile
- script: make -C cppEDM/src -f makefile.windows
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: building cppEDM on windows
- script: make -C cppEDM/src
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: building cppEDM on macOS

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'

#build the package and download
- script: pip install pybind11 --user
- script: pip install wheel --user
- script: python setup.py bdist_wheel
- script: python setup.py install --user
- script: python pyEDM/tests/tests.py

- publish: $(System.DefaultWorkingDirectory)/dist
  condition: eq( variables['Agent.OS'], 'Darwin' )
  artifact: $(build_name)
- publish: $(System.DefaultWorkingDirectory)/dist
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  artifact: $(build_name)
